namespace Onwrd.EntityFrameworkCore.Internal.Migrations.Updates
{
    internal class CreateSchema : IOnwrdMigrationUpdate
    {
        public string GetSqlForMsSqlServer()
        {
            // Schema auto-generated by EF 
            return null;
        }

        public string GetSqlForPostgreSql()
        {
            // Schema auto-generated by EF 
            return "CREATE SCHEMA Onwrd";
        }
    }
}
