namespace Onwrd.EntityFrameworkCore.Internal.Migrations.Updates
{
    internal class CreateSchema : IOnwrdMigrationUpdate
    {
        public string GetSqlForMsSqlServer()
        {
            // Schema auto-generated by EF when EF migrations table is initialized
            return null;
        }

        public string GetSqlForPostgreSql()
        {
            // Schema auto-generated by EF when EF migrations table is initialized
            return null;
        }
    }
}
